# Configuració del lloc
site_name: El web del Professor
site_author: JB Talens
site_url: https://juatafe.github.io/elweb

# Tema
theme:
  name: material
  logo: img/logos/logoJust.png  # Afegeix el logo principal
  favicon: img/logos/logo50.ico  # Favicon
  language: ca
  features:
    - navigation.top
    - navigation.footer  # Afegeix peu de pàgina
    - toc.follow
    - content.code.copy
  palette:
    # Tornant als colors originals (morat i taronja)
    - scheme: default
      primary: 'purple'
      accent: 'orange'
      toggle:
        icon: material/brightness-7 
        name: Mode oscur
    - scheme: slate
      primary: 'purple'
      accent: 'orange'
      toggle:
        icon: material/brightness-4
        name: Mode clar

# Footer amb logos
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:jb.talensfelis@edu.gva.es
      name: Contacte
  consent:
    title: Consentiment de Cookies
    description: Utilitzem cookies per reconèixer les vostres visites i preferències repetides.
  copyright: by JB.Talens es troba sota llicència CC BY-NC-SA 4.0 - <a href="#__consent">Canvia la configuració de les cookies</a>

  # Afegeix els logos al peu de pàgina
  extra_footer: |
    <div class="footer-logos">
      <img src="img/logos/gvaVertical.png" alt="Logo GVA" class="footer-logo">
      <img src="img/logos/GvaNext.png" alt="Logo NextGen" class="footer-logo">
      <img src="img/logos/miniPla.png" alt="Logo Pla Recuperació" class="footer-logo">
      <img src="img/logos/logoJust.png" alt="Logo Institut" class="footer-logo">
    </div>

# Extensions de Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# Estils personalitzats addicionals
extra_css:
  - css/custom.css  # Afegeix aquest fitxer CSS per personalitzar la posició dels logos

# Plugins
plugins:
  - search
  - social
