site_name: Diseño curricular de la Tecnología y la Informática
site_author: JB Talens
site_url: https://juatafe.github.io/elweb/DCTI

theme:
  name: material
  logo: "docs/img/logos/LOGO-CAMPUS-GANDIAgrisV.png"
  favicon: "docs/img/favicon.ico"
  language: ca
  features:
    - navigation.top # Botó de "Back to top"
    - navigation.footer
    - toc.follow
    - content.code.copy
  palette: 
    - scheme: default
      primary: "#003399"  # Azul UPV
      accent: "#f0f0f0"   # Gris claro UPV
      toggle:
        icon: material/brightness-7 
        name: Mode clar
    - scheme: slate
      primary: "#003399"  # Azul UPV
      accent: "#f0f0f0"   # Gris claro UPV
      toggle:
        icon: material/brightness-4
        name: Mode oscur

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:jb.talensfelis@edu.gva.es
      name: Contacte
  consent:
    title: Consentiment de Cookies
    description: Utilitzem cookies per reconèixer les vostres visites i preferències repetides.
  copyright: Apunts DCTI - 2nFPB by JB.Talens es troba sota llicència CC BY-NC-SA 4.0 - <a href="#__consent">Canvia la configuració de les cookies</a>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Index: index.md
  

extra_css:
  - css/upv_styles.css

plugins:
  - search
  - social
