site_name: Diseño curricular de la Tecnología y la Informática
site_author: JB Talens
site_url: https://juatafe.github.io/elweb/DCTI

theme:
  name: readthedocs
  logo: "img/logos/marca_UPV_secundaria_blanco300.png"
  favicon: "img/favicon.ico"
  language: es
  features:
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
  palette: 
    - scheme: default
      primary: '#CC0033'  # 
      accent: '#f0f0f0'   # Gris claro UPV
      toggle:
        icon: material/brightness-7 
        name: Mode clar
    - scheme: slate
      primary: '#CC0033'  # 
      accent: '#f0f0f0'   # Gris claro UPV
      toggle:
        icon: material/brightness-1
        name: Mode oscur

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:jb.talensfelis@edu.gva.es
      name: Contacte
  consent:
    title: Consentimiento de Cookies
    description: Utilizamos cookies para mejorar su experiencia de navegación.
  copyright: Apunts DCTI by JB.Talens está bajo licencia CC BY-NC-SA 4.0 - <a href="#__consent">Cambiar la configuración de las cookies</a>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Index: index.md

extra_css:
  - https://juatafe.github.io/elweb/docs/ccs/extra_css_pdf.css

plugins:
  - search
